var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(m){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.inherits=function(a,b){a.prototype=$jscomp.objectCreate(b.prototype);a.prototype.constructor=a;if($jscomp.setPrototypeOf){var m=$jscomp.setPrototypeOf;m(a,b)}else for(m in b)if("prototype"!=m)if(Object.defineProperties){var n=Object.getOwnPropertyDescriptor(b,m);n&&Object.defineProperty(a,m,n)}else a[m]=b[m];a.superClass_=b.prototype};var music={menu:0,game:0};CloudAPI.init({id:825,splash:!1});CloudAPI.mute=function(){music.menu&&music.menu.setMute(!0);return!0};
CloudAPI.unmute=function(){music.menu&&music.menu.setMute(!1);return!0};function show_ad(){CloudAPI&&(CloudAPI.gameOver(),CloudAPI.gameOver(),CloudAPI.gameOver(),CloudAPI.gameOver())}
var url=new URL(window.location.href),_params=url.searchParams.get("data"),jsondata=JSON.parse(_params),global_state="ready",cur_coin=0,game_data={sound:!0,music:!0,player_data:{unlocked_ship:1,selected_ship:1},upgrades:{ship:[{fire_power:1,fire_rate:1},{fire_power:1,fire_rate:1},{fire_power:1,fire_rate:1},{fire_power:1,fire_rate:1},{fire_power:1,fire_rate:1}],coin_value:1,bonus_value:1},ship_price:[0,1E5,8E5,2E6],upgrade_price:1.13,coin:0,coin_price:20,power_price:30,level:1,cur_coin:0,life:1,total_level:200},
_sv=localStorage.getItem("rf_antivirus");null!=_sv&&(game_data=JSON.parse(_sv));var Boot=function(){return Phaser.Scene.call(this,"boot")||this};$jscomp.inherits(Boot,Phaser.Scene);Boot.prototype.preload=function(){var a=this;this.load.image("bg","assets/bg.png");this.load.image("game_title","assets/game_title.png");this.load.image("btn_start","assets/btn_start.png");this.load.on("complete",function(){a.scale.stopListeners();a.scene.start("preload")},this)};
var Load=function(){return Phaser.Scene.call(this,"preload")||this};$jscomp.inherits(Load,Phaser.Scene);
Load.prototype.preload=function(){var a=this;if(CloudAPI.logos.active()){var b=CloudAPI.logos.list();console.log(b)}b&&this.load.image("logo",b.horizontal);this.add.sprite(360,540,"bg");this.add.sprite(360,250,"game_title");var m=this.add.rectangle(config.width/2,500,600,20);m.setStrokeStyle(4,16777215);m.alpha=.7;var n=this.add.rectangle(config.width/2,500,590,10,16777215);n.alpha=.8;this.load.on("progress",function(a){n.width=590*a});this.load.on("complete",function(){m.destroy();n.destroy();var b=
draw_button(360,640,"start",a);a.tweens.add({targets:b,alpha:.5,yoyo:!0,duration:300,loop:-1})},this);this.input.on("gameobjectdown",function(){a.scene.start("game")},this);for(b=1;4>=b;b++)this.load.image("ship"+b,"assets/ship"+b+".png"),this.load.image("enemy"+b,"assets/enemy"+b+".png");this.load.image("level_bar","assets/level_bar.png");this.load.image("popup","assets/popup.png");this.load.image("hit","assets/hit.png");this.load.image("coin","assets/coin.png");this.load.image("footer","assets/footer.png");
this.load.image("coin_icon","assets/coin_icon.png");this.load.image("bullet_icon","assets/bullet_icon.png");this.load.image("progress","assets/progress.png");this.load.image("progressbar","assets/progressbar.png");this.load.image("coin_bar","assets/coin_bar.png");this.load.image("power_bar","assets/power_bar.png");this.load.image("diamond_bar","assets/diamond_bar.png");this.load.image("btn_setting","assets/btn_setting.png");this.load.image("btn_tab","assets/btn_tab.png");this.load.image("btn_list",
"assets/btn_list.png");this.load.image("btn_ship","assets/btn_ship.png");this.load.image("btn_play","assets/btn_play.png");this.load.image("btn_on","assets/btn_on.png");this.load.image("btn_off","assets/btn_off.png");this.load.image("btn_close","assets/btn_close.png");this.load.image("btn_collect","assets/btn_collect.png");this.load.image("btn_more","assets/btn_more.png");this.load.image("btn_ship_active","assets/btn_ship_active.png");this.load.spritesheet("bullet","assets/bullet.png",{frameWidth:19,
frameHeight:34});this.load.spritesheet("explosion","assets/explosion.png",{frameWidth:380,frameHeight:380});this.load.spritesheet("powerups","assets/powerups.png",{frameWidth:64,frameHeight:64});this.load.spritesheet("power_active","assets/power_active.png",{frameWidth:64,frameHeight:64});for(b=1;b<=game_data.total_level;b++)this.load.json("level-"+b,"level/level-"+b+".json");this.load.audio("hit","audio/hit.mp3");this.load.audio("shoot","audio/shoot.mp3");this.load.audio("powerup","audio/powerup.mp3");
this.load.audio("explosion","audio/explosion.mp3");this.load.audio("finish","audio/finish.mp3");this.load.audio("collect","audio/collect.mp3");this.load.audio("click","audio/click.mp3");this.load.audio("upgrade","audio/upgrade.mp3");this.load.audio("EpicArpg","audio/EpicArpg.mp3");this.load.audio("coin","audio/coin.mp3")};var UI=function(){return Phaser.Scene.call(this,"ui")||this};$jscomp.inherits(UI,Phaser.Scene);
UI.prototype.create=function(){function a(e,d){for(var a=0;a<d;a++)e*=game_data.upgrade_price;return Math.round(e)}function b(e){var d=!1;if("fire_power"===e||"fire_rate"===e){var b=a(game_data.power_price+30*(game_data.player_data.selected_ship-1),game_data.upgrades.ship[game_data.player_data.selected_ship][e]);b<=game_data.coin?(game_data.coin-=b,D.setText(n(game_data.coin)),d=!0):alert("No enough coin!")}if("coin_value"===e||"bonus_value"===e)b=a(game_data.coin_price,game_data.upgrades[e]),b<=
game_data.coin?(game_data.coin-=b,D.setText(n(game_data.coin)),d=!0):alert("No enough coin!");if(d){play_sound("upgrade",l);"coin_value"===e||"bonus_value"===e?game_data.upgrades[e]++:game_data.upgrades.ship[game_data.player_data.selected_ship][e]++;var f,h;d=x.getLength();b=x.getChildren();for(var k=0;k<d;k++)b[k].name==="txt_"+e&&(f=b[k]),b[k].name==="cost_"+e&&(h=b[k]);if("fire_power"===e){var g="FIRE POWER [ LVL "+game_data.upgrades.ship[game_data.player_data.selected_ship].fire_power+" ]";var m=
n(a(game_data.power_price+30*(game_data.player_data.selected_ship-1),game_data.upgrades.ship[game_data.player_data.selected_ship].fire_power))}else"fire_rate"===e?(g="FIRE RATE [ LVL "+game_data.upgrades.ship[game_data.player_data.selected_ship].fire_rate+" ]",m=n(a(game_data.power_price+30*(game_data.player_data.selected_ship-1),game_data.upgrades.ship[game_data.player_data.selected_ship].fire_rate))):"coin_value"===e?(g="COIN VALUE [ LVL "+game_data.upgrades.coin_value+" ]",m=n(a(game_data.coin_price,
game_data.upgrades.coin_value))):"bonus_value"===e&&(g="BONUS VALUE [ LVL "+game_data.upgrades.bonus_value+" ]",m=n(a(game_data.coin_price,game_data.upgrades.bonus_value)));f.setText(g);h.setText(m);save_data()}}function m(e){z.clear(!0,!0);x.clear(!0,!0);if(G!=e){G=e;var d=340;if("ship"===e)for(d=268,e=0;5>e;e++){var b=draw_button(80+140*e,884,"ship",l);b.name="select_ship";b.id=e+1;b.selected=!1;e+1==game_data.player_data.selected_ship&&(b.setTexture("btn_ship_active"),b.selected=!0);z.add(b);if(4>
e){var f=l.add.sprite(b.x,b.y,"ship"+(e+1));f.name="ship_icon"+(e+1);e>=game_data.player_data.unlocked_ship&&(f.alpha=.7,b.alpha=.7);z.add(f)}else b.alpha=.7}else{b=draw_button(360,896,"list",l);f=draw_button(360,796,"list",l);var g=l.add.text(50,896,"",{fontFamily:"impact",fontSize:30,align:"left",color:"#fff"}).setOrigin(0,.5),k=l.add.text(50,798,"",{fontFamily:"impact",fontSize:30,align:"left",color:"#fff"}).setOrigin(0,.5),h=l.add.text(580,896,"",{fontFamily:"impact",fontSize:30,align:"left",
color:"#fff"}).setOrigin(0,.5),m=l.add.text(580,798,"",{fontFamily:"impact",fontSize:30,align:"left",color:"#fff"}).setOrigin(0,.5);"power"===e?(b.name="fire_rate",f.name="fire_power",g.name="txt_fire_rate",k.name="txt_fire_power",h.name="cost_fire_rate",m.name="cost_fire_power",g.setText("FIRE RATE [ LVL "+game_data.upgrades.ship[game_data.player_data.selected_ship].fire_rate+" ]"),k.setText("FIRE POWER [ LVL "+game_data.upgrades.ship[game_data.player_data.selected_ship].fire_power+" ]"),h.setText(n(a(game_data.power_price+
30*(game_data.player_data.selected_ship-1),game_data.upgrades.ship[game_data.player_data.selected_ship].fire_rate))),m.setText(n(a(game_data.power_price+30*(game_data.player_data.selected_ship-1),game_data.upgrades.ship[game_data.player_data.selected_ship].fire_power)))):(b.name="bonus_value",f.name="coin_value",g.name="txt_bonus_value",k.name="txt_coin_value",h.name="cost_bonus_value",m.name="cost_coin_value",g.setText("BONUS VALUE [ LVL "+game_data.upgrades.bonus_value+" ]"),k.setText("COIN VALUE [ LVL "+
game_data.upgrades.coin_value+" ]"),h.setText(n(a(game_data.coin_price,game_data.upgrades.bonus_value))),m.setText(n(a(game_data.coin_price,game_data.upgrades.coin_value))));x.addMultiple([b,f,g,k,h,m])}q.displayHeight=d}else G="",q.displayHeight=140}function n(b){return 1E5<=b?Math.round(b/1E3)+"K":b}function F(){r="setting";var b=l.add.rectangle(0,0,720,1080,0,.7).setOrigin(0),d=l.add.sprite(360,540,"popup"),a=draw_button(500,436,"on",l);a.name="sound";I(a.name,a);var f=draw_button(500,500,"on",
l);f.name="music";I(f.name,f);var g=l.add.text(184,a.y,"Sound",{fontFamily:"impact",fontSize:35,align:"left",color:"#fff"}).setOrigin(0,.5),k=l.add.text(184,f.y,"Music",{fontFamily:"impact",fontSize:35,align:"left",color:"#fff"}).setOrigin(0,.5),h=draw_button(360,628,"close",l);M.addMultiple([b,d,a,f,h,g,k])}function J(b,d){game_data[b]?(game_data[b]=!1,d.setTexture("btn_off"),"music"===b&&stop_music("menu")):(game_data[b]=!0,d.setTexture("btn_on"),"music"===b&&play_music("EpicArpg",l,"menu"))}function I(b,
d){game_data[b]?d.setTexture("btn_on"):d.setTexture("btn_off")}play_music("EpicArpg",this,"menu");var A=this.scene.get("game"),l=this,K=this.add.container(),H=this.add.container(),z=this.add.group(),x=this.add.group(),M=this.add.group(),G="",r="main",L=!1,Q=draw_button(360,750,"more",this),N=this.add.sprite(360,860,"logo").setInteractive();N.name="logo";N.setScale(.5);this.add.sprite(620,40,"coin_bar");this.add.sprite(450,40,"diamond_bar");draw_button(40,40,"setting",this);var D=l.add.text(590,40,
String(n(game_data.coin)),{fontFamily:"impact",fontSize:25,align:"left",color:"#fff"}).setOrigin(0,.5),O=l.add.text(430,40,String(game_data.life),{fontFamily:"impact",fontSize:25,align:"left",color:"#fff"}).setOrigin(0,.5);A.events.on("_update",function(b){"coin"===b&&D.setText(cur_coin);"life"===b&&(0>game_data.life&&(game_data.life=0),O.setText(game_data.life))});A.events.on("completed",function(b){r="main";game_data.level++;D.setText(n(game_data.coin));l.tweens.add({targets:H,y:0,duration:500,
ease:"Sine.easeIn"});t.setVisible(!1);u.setVisible(!0);w.setVisible(!0);u.setText(cur_coin);q.displayHeight=140;G="";setTimeout(function(){R.setText(game_data.level-1);E.setText(game_data.level);y.setText(game_data.level+1)},2E3);save_data();play_music("EpicArpg",l,"menu")});A.events.on("gameover",function(b){r="main";D.setText(n(game_data.coin));l.tweens.add({targets:H,y:0,duration:500,ease:"Sine.easeIn"});t.setVisible(!1);u.setVisible(!0);w.setVisible(!0);u.setText(cur_coin);q.displayHeight=140;
G="";save_data();play_music("EpicArpg",l,"menu")});A=this.add.sprite(360,250,"game_title");var B=this.add.sprite(360,480,"level_bar"),R=this.add.text(207,480,String(game_data.level-1),{fontFamily:"impact",fontSize:40,align:"center",color:"#fff"}).setOrigin(.5),E=this.add.text(360,480,String(game_data.level),{fontFamily:"impact",fontSize:60,align:"center",color:"#fff"}).setOrigin(.5),y=this.add.text(513,480,String(game_data.level+1),{fontFamily:"impact",fontSize:40,align:"center",color:"#fff"}).setOrigin(.5),
t=draw_button(360,640,"play",this),u=this.add.text(240,680,"100000",{fontFamily:"impact",fontSize:40,align:"left",color:"#fff"}).setOrigin(0,.5),w=draw_button(360,680,"collect",this);u.setVisible(!1);w.setVisible(!1);this.tweens.add({targets:t,alpha:.5,yoyo:!0,duration:300,loop:-1});H.add([A,B,R,E,y,t,w,u]);var q=l.add.rectangle(360,1080,720,140,0).setOrigin(.5,1);q.alpha=.3;A=this.add.sprite(360,1014,"footer");A.alpha=.8;B=draw_button(128,1010,"tab",this);B.name="ship";B.alpha=.7;B.tab=!0;var h=
this.add.sprite(B.x,B.y,"ship"+game_data.player_data.selected_ship),C=draw_button(360,1010,"tab",this);C.name="power";C.alpha=.7;C.tab=!0;var g=this.add.sprite(C.x,C.y,"bullet_icon"),v=draw_button(592,1010,"tab",this);v.name="coin";v.alpha=.7;v.tab=!0;var S=this.add.sprite(v.x,v.y,"coin_icon");K.add([q,A,B,h,C,g,v,S,Q,N]);this.input.on("gameobjectdown",function(a,d){if("main"===r)if(d.tab?(play_sound("click",l),K.iterate(function(b){b.tab&&(b.alpha=.7)}),d.alpha=1,m(d.name)):"more"===d.name&&CloudAPI.links.active()&&
window.open(CloudAPI.links.list().games),"logo"===d.name)CloudAPI.links.active()&&window.open(CloudAPI.links.list().logo);else{if(d.button)if("collect"===d.name){show_ad();play_sound("collect",l);game_data.coin+=cur_coin;var g=cur_coin=0,f=setInterval(function(){var b=l.add.sprite(w.x-140,w.y,"coin");l.tweens.add({targets:b,x:560,y:40,duration:600,ease:"Sine.easeIn",onComplete:function(){b.destroy(!0)}});g++;5===g&&(t.setVisible(!0),u.setVisible(!1),w.setVisible(!1),clearInterval(f))},100);D.setText(n(game_data.coin));
l.tweens.add({targets:K,y:0,duration:1E3,ease:"Sine.easeIn"});save_data()}else if("play"===d.name)d=function(){r="play";l.events.emit("play");l.tweens.add({targets:H,y:-800,duration:500,ease:"Sine.easeOut"});l.tweens.add({targets:K,y:1680,duration:500,ease:"Sine.easeOut"});x.clear(!0,!0);z.clear(!0,!0);save_data()},stop_music("menu"),game_data.level<=game_data.total_level?d():confirm("You've reached the last level. Do you want to start from level 1?")&&(game_data.level=1,d());else if("fire_rate"===
d.name||"fire_power"===d.name||"coin_value"===d.name||"bonus_value"===d.name)b(d.name);else if("select_ship"===d.name){if(play_sound("click",l),x.clear(!0,!0),q.displayHeight=268,!d.selected&&5!=d.id)if(d.id<=game_data.player_data.unlocked_ship){a=z.getLength();for(var e=z.getChildren(),k=0;k<a;k++)e[k].selected&&(e[k].selected=!1,e[k].setTexture("btn_ship"));d.selected=!0;d.setTexture("btn_ship_active");game_data.player_data.selected_ship=d.id;h.setTexture("ship"+d.id)}else e=n(game_data.ship_price[d.id-
1]),d.id>game_data.player_data.unlocked_ship+1&&(e="-"),a=draw_button(360,772,"list",l),"-"!=e&&(a.name="buy_ship"),a.id=d.id,d=l.add.sprite(80,772,"ship"+d.id),d.setScale(.7),e=l.add.text(580,772,String(e),{fontFamily:"impact",fontSize:30,align:"left",color:"#fff"}).setOrigin(0,.5),x.addMultiple([a,d,e]),q.displayHeight=370}else if("buy_ship"===d.name)if(game_data.ship_price[d.id-1]<=game_data.coin){play_sound("upgrade",l);game_data.coin-=game_data.ship_price[d.id-1];D.setText(n(game_data.coin));
game_data.player_data.unlocked_ship++;a=z.getLength();e=z.getChildren();for(k=0;k<a;k++)e[k].selected&&(e[k].selected=!1,e[k].setTexture("btn_ship")),"select_ship"===e[k].name&&e[k].id===d.id&&(e[k].selected=!0,e[k].setTexture("btn_ship_active"),e[k].alpha=1),e[k].name==="ship_icon"+d.id&&(e[k].alpha=1);game_data.player_data.selected_ship=d.id;h.setTexture("ship"+d.id);x.clear(!0,!0);q.displayHeight=268;save_data()}else alert("No enough coin!");else"setting"===d.name&&(play_sound("click",l),F())}else if("setting"===
r)if("close"===d.name)play_sound("click",l),save_data(),M.clear(!0,!0),L?(L=!1,r="play",l.events.emit("resume_game")):r="main";else{if("music"===d.name||"sound"===d.name)play_sound("click",l),J(d.name,d)}else"play"===r&&"play"===global_state&&"setting"===d.name&&(play_sound("click",l),L=!0,F(),l.events.emit("pause_game"))})};var Game=function(){return Phaser.Scene.call(this,"game")||this};$jscomp.inherits(Game,Phaser.Scene);
Game.prototype.create=function(){var a,b,m,n,F,J,I;function A(){y.width=350;y.setVisible(!1);E.setVisible(!1);I=J=F=!1;global_state="ready";t=!0;w=u=0;q=1;m=b=a=C=0;n=!1;g=[0,0,0,0,0];v&&clearInterval(v);S=null!=jsondata?jsondata:h.cache.json.get("level-"+game_data.level);e=S.array;for(var c=0;20>c;c++)for(var p=0;20>p;p++)e[c][p]&&u++;f.ready=!0}function l(){n=!1;b=0;v=setInterval(function(){if(!t){for(var c=!1,p=b;20>p;p++){if(0!=e[a][p]){c=!0;break}19===p&&(n=!0)}c?e[a][b]&&H(e[a][b].amount,e[a][b].type):
(n=!0,clearInterval(v));b++}},500)}function K(c,b){if(20>=Math.round(100*Math.random())){var p=Math.floor(6*Math.random());5===p&&75>=Math.round(100*Math.random())&&(p=4);var a=h.physics.add.sprite(c,b,"powerups");T.add(a);a.setFrame(p);a.setCollideWorldBounds(!0);a.setBounce(1,1);a.lifetime=10;a.setVelocity(Phaser.Math.Between(-100,150),Phaser.Math.Between(50,100));setTimeout(function(){h.tweens.add({targets:a,alpha:0,duration:2E3,onComplete:function(){a.destroy(!0)}})},5E3)}}function H(c,b,a,e){var p=
[50,120];2===b?(p[0]=200,p[1]=300):1!=b&&(p=[70,180]);m++;C++;var f=Math.floor(3*Math.random())+1;e&&(f=e);e=Math.round(400*Math.random())+200;var g=-200;a&&(e=a.x,g=a.y);a=h.physics.add.sprite(e,g,"enemy"+b);d.add(a);a.type=b;a.setCircle(80,70,70);a.setScale(1/f);a.scale=1/f;a.sc=f;a.enemy=!0;a.setCollideWorldBounds(!0);a.setBounce(1,1);a.life=c;a.def_life=c;a.color_id=Math.round(15*Math.random());Q(a);a.id=C;a.rotate=0;a.rotate_min=4*Math.random()-3;a.setVelocity(Phaser.Math.Between(-100,150),Phaser.Math.Between(p[0],
p[1]));I&&(a.body.velocity.x/=2,a.body.velocity.y/=2);a.txt=h.add.text(a.x,a.y,r(a.life),{fontFamily:"impact",fontSize:65,align:"center",color:"#fff"});a.txt.setOrigin(.5);a.txt.setScale(1/f);z(a)}function z(c){c.update=function(){this.y>config.height+310&&(this.y=-310,4===this.type&&(this.life+=Math.round(this.life/2),this.life>this.def_life&&(this.life=this.def_life),this.txt.setText(r(this.life))));this.txt.setPosition(this.x,this.y);this.rotate+=this.rotate_min;360<this.rotate&&(this.rotate=0);
this.rotation=Math.PI/180*this.rotate}}function x(){for(var c=0;c<g.length;c++)0!=g[c]&&(g[c].bar.destroy(!0),g[c].icon.destroy(!0),g[c].rect.destroy(!0),g[c]=0)}function M(c){for(var a=d.getLength(),b=d.getChildren(),e=0;e<a;e++){var f=b[e];f.body.velocity.x/=c;f.body.velocity.y/=c}}function G(c){var b=Math.floor(game_data.upgrades.ship[game_data.player_data.selected_ship].fire_power)+1;J&&(b*=5);c.life-=b;if(0>=c.life){play_sound("explosion",h);K(c.x,c.y);cur_coin+=Math.round(c.def_life/10*(game_data.upgrades.coin_value/
10+1));h.events.emit("_update","coin");var d=h.add.sprite(c.x,c.y,"explosion");d.setScale(c.scale);d.setBlendMode(Phaser.BlendModes.ADD);d.play("exp");d.on("animationcomplete",function(){d.destroy(!0,!0)});3===c.type&&75>100*Math.random()&&(u+=2,b=c.sc,2>=b&&(b*=2),H(Math.round(c.def_life/2),1,{x:c.x,y:c.y},b),H(Math.round(c.def_life/2),1,{x:c.x,y:c.y},b));c.txt.destroy(!0);c.destroy(!0);w++;y.width=Math.round(350-w/u*350);m--;if(0===m&&n){a++;b=!1;for(var f=0;20>f;f++)if(e[a][f].amount){b=!0;break}b&&
l()}w===u&&N()}else if(F&&(cur_coin+=Math.round(1+game_data.upgrades.bonus_value/10)),!c.tween){play_sound("hit",h);if(F){play_sound("coin",h);h.events.emit("_update","coin");var g=h.add.sprite(c.x,c.y,"coin");h.tweens.add({targets:g,x:560,y:40,duration:1E3,ease:"Back.easeIn",onComplete:function(){g.destroy(!0)}})}c.y-=10;c.tween=!0;h.tweens.add({targets:c,scaleX:c.scale-.05,scaleY:c.scale-.05,yoyo:!0,duration:50,ease:"Linear",onComplete:function(){c.tween=!1}});Q(c);c.txt.setText(r(c.life))}}function r(c){return String(1E3<=
c?Math.round(c/1E3*10)/10+"K":Math.round(c))}function L(c){var a=h.add.sprite(c.x,c.y-30,"hit");a.rotation=Math.PI/180*Math.round(360*Math.random());h.tweens.add({targets:a,scaleX:0,scaleY:0,duration:200,ease:"Linear",onComplete:function(){a.destroy(!0)}})}function Q(c){var a=[16724787,16724828,16724858,16724889,16724920,16266239,13382655,10695679,7353343,4469759,3362559,3369471,3377407,3388671,2736895,2745087,3009511,3009471,3009430,3009385,3201852,8054837,10476343,14084923,15454523,16761915,16747561,
16735017,16728617];c.color_id>=a.length-1?c.color_id=0:c.color_id++;c.setTint(a[c.color_id])}function N(){play_sound("finish",h);x();clearInterval(v);global_state="completed";t=!0;setTimeout(function(){h.tweens.add({targets:f,y:-100,duration:1E3,ease:"Sine.easeIn",onComplete:function(){y.setVisible(!1);E.setVisible(!1);h.events.emit("completed")}})},2E3)}function D(){x();clearInterval(v);global_state="gameover";t=!0;f.setVisible(!1);M(1E3);setTimeout(function(){y.setVisible(!1);E.setVisible(!1);var c=
d.getLength(),a=d.getChildren();for(--c;0<=c;c--){var b=a[c];b.txt.destroy(!0,!0);b.destroy(!0,!0)}h.events.emit("gameover")},2E3)}this.scene.launch("ui");var O=this.scene.get("ui"),B=new Phaser.Class({Extends:Phaser.Physics.Arcade.Image,initialize:function(c){Phaser.Physics.Arcade.Image.call(this,c,0,0,"bullet");this.speed=1E3;this.bullet=!0},fire:function(c,a,b,d){this.setFrame(b);this.setPosition(c,a-50);this.setActive(!0);this.setVisible(!0);this.setAngle(d-270);c=Phaser.Math.DegToRad(d);this.scene.physics.velocityFromRotation(c,
this.speed,this.body.velocity);this.body.velocity.x*=2;this.body.velocity.y*=2},update:function(c,a){0>this.y&&(this.setActive(!1),this.setVisible(!1),this.body.stop());if(0>this.x||this.y>config.height)this.setActive(!1),this.setVisible(!1),this.body.stop()}}),R=this.add.tileSprite(0,-config.height,config.width,2*config.height,"bg").setOrigin(0),E=this.add.sprite(360,120,"progressbar"),y=this.add.tileSprite(185,120,350,11,"progress").setOrigin(0,.5);y.setVisible(!1);E.setVisible(!1);E.setDepth(1);
y.setDepth(1);var t=!0,u,w,q,h=this,C,g,v,S,e;h.tweens.add({targets:R,y:0,duration:25E3,loop:-1});var d=this.physics.add.group({runChildUpdate:!0}),T=this.physics.add.group({runChildUpdate:!0});this.add.group();this.anims.create({key:"exp",frames:this.anims.generateFrameNumbers("explosion"),frameRate:25});var f=this.physics.add.sprite(360,config.height+100,"ship"+game_data.player_data.selected_ship);f.body.setSize(30,60,!0);O.events.on("play",function(c){console.log("lvl "+game_data.level);A();h.events.emit("_update",
"coin");f.setTexture("ship"+game_data.player_data.selected_ship);f.setPosition(360,config.height+100);f.setVisible(!0);h.tweens.add({targets:f,y:900,duration:800,ease:"Sine.easeOut",onComplete:function(){global_state="play";t=!1;E.setVisible(!0);y.setVisible(!0)}});l()});O.events.on("pause_game",function(){"play"===global_state&&h.scene.pause()});O.events.on("resume_game",function(){"play"===global_state&&h.scene.resume()});var P=!1,k=this.physics.add.group({classType:B,runChildUpdate:!0}),U=0,V=
0,W=0,X=0;this.physics.world.checkCollision.up=!1;this.physics.world.checkCollision.down=!1;this.physics.world.on("worldbounds",function(c,a,b,d,e){b&&console.log("ff")});this.physics.add.overlap(d,k,function(c,a){a.bullet&&(L(a),a.setActive(!1),a.setVisible(!1),a.y=-400,G(c));c.bullet&&(L(c),c.setActive(!1),c.setVisible(!1),c.y=-400,G(a))});this.physics.add.overlap(T,f,function(c,a){if("play"===global_state){play_sound("powerup",h);c=a.frame.name;a.destroy(!0);a=-1;for(var b=0;b<g.length;b++)if(0!=
g[b]&&g[b].data.type===c){a=-2;g[b].data.time=100;break}if(-1===a)for(b=0;b<g.length;b++)if(0===g[b]){a=b;break}0<=a&&(0===c?(I=!0,M(2)):1===c?q=3:2===c?F=!0:3===c?J=!0:4===c?q=0:5===c&&(game_data.life++,h.events.emit("_update","life"),g[a]=0),5!=c&&(b=120+80*a,g[a]={},g[a].data={time:100,type:c},g[a].bar=h.add.sprite(660,b,"power_bar"),g[a].icon=h.add.sprite(660,b-6,"power_active"),g[a].icon.setFrame(c),g[a].rect=h.add.rectangle(660,b+25,70,5,10027007)))}});this.physics.add.overlap(d,f,function(c,
a){if(c.ready){if(0>=game_data.life){play_sound("explosion",h);var b=h.add.sprite(c.x,c.y,"explosion");b.setScale(.4);b.setBlendMode(Phaser.BlendModes.ADD);b.play("exp");b.on("animationcomplete",function(){b.destroy(!0,!0)});D()}game_data.life--;h.events.emit("_update","life");c.ready=!1;var d=0,e=setInterval(function(){c.alpha=0===d%2?0:1;d++;25<=d&&(c.ready=!0,c.alpha=1,clearInterval(e))},100)}});this.input.on("pointerdown",function(c){U=c.x;V=c.y;W=f.x;X=f.y;P=!0});this.input.on("pointerup",function(c){P=
!1});this.input.on("pointerupoutside",function(c){P=!1});this.input.on("pointermove",function(c){if(P&&"play"===global_state){var a=W+(c.x-U);c=X+(c.y-V);0>a?a=0:a>config.width&&(a=config.width);0>c?c=0:c>config.height&&(c=config.height);f.setPosition(a,c)}});setInterval(function(){if(!t){play_sound("shoot",h);var a=0;J&&(a=1);for(var b=q,d=-1*b;d<=b;d++){var e=k.get();e&&e.fire(f.x+20*d,f.y+20,a,270)}2===game_data.player_data.selected_ship?((b=k.get())&&b.fire(f.x+50,f.y+40,a,310),(b=k.get())&&b.fire(f.x-
50,f.y+40,a,220)):3===game_data.player_data.selected_ship?((b=k.get())&&b.fire(f.x+50,f.y+40,a,290),(b=k.get())&&b.fire(f.x-50,f.y+40,a,240),(b=k.get())&&b.fire(f.x+50,f.y+70,a,0),(b=k.get())&&b.fire(f.x-50,f.y+70,a,180)):4===game_data.player_data.selected_ship&&((b=k.get())&&b.fire(f.x+50,f.y+40,a,290),(b=k.get())&&b.fire(f.x-50,f.y+40,a,250),(b=k.get())&&b.fire(f.x+50,f.y+70,a,320),(b=k.get())&&b.fire(f.x-50,f.y+70,a,210),(b=k.get())&&b.fire(f.x+50,f.y+70,a,30),(b=k.get())&&b.fire(f.x-50,f.y+70,
a,150))}},150-game_data.upgrades.ship[game_data.player_data.selected_ship].fire_rate);setInterval(function(){if(!t)for(var a=0;a<g.length;a++)if(0!=g[a])if(g[a].data.time-=2,0>=g[a].data.time){if(0===g[a].data.type){I=!1;for(var b=d.getLength(),e=d.getChildren(),f=0;f<b;f++){var h=e[f];h.body.velocity.x*=2;h.body.velocity.y*=2}}else 1===g[a].data.type?q=1:2===g[a].data.type?F=!1:3===g[a].data.type?J=!1:4===g[a].data.type&&(q=1);g[a].bar.destroy(!0);g[a].icon.destroy(!0);g[a].rect.destroy(!0);g[a]=
0}else g[a].rect.width=.7*g[a].data.time},300);this.input.keyboard.on("keydown",function(a){"q"===a.key&&(this.physics.world.timeScale=.3)},this);this.input.keyboard.on("keyup",function(a){"q"===a.key&&(this.physics.world.timeScale=1)},this)};function save_data(a){localStorage.setItem("rf_antivirus",JSON.stringify(game_data))}function play_sound(a,b){game_data.sound&&b.sound.play(a)}
function play_music(a,b,m){game_data.music&&music[m]&&music[m].isPlaying&&music[m].stop();game_data.music&&(music[m]=b.sound.add(a,{loop:!0}),music[m].play())}function stop_music(a){music[a]&&music[a].stop()}function draw_button(a,b,m,n){a=n.add.sprite(a,b,"btn_"+m);a.setInteractive();a.name=m;a.button=!0;return a}
var config={type:Phaser.AUTO,width:720,height:1080,physics:{default:"arcade",arcade:{debug:!1,fps:60,gravity:!1}},scale:{mode:Phaser.Scale.FIT,parent:"redfoc",autoCenter:Phaser.Scale.CENTER_BOTH},scene:[Boot,Load,Game,UI]},game=new Phaser.Game(config);
